qnx: remove features not used by QNX
- /usr merge, no longer using /bin, /sbin, /lib, /usr/sbin and /usr/libexec
  - also applies to openrc
- add qnx target triplets
- remove -pyc auto splitting
- remove auto so dependency, only prompt a warning
- remove capability detections
- remove nftables auto splitting
- remove multi-libc support

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -1,4 +1,4 @@
-#!/bin/ash -e
+#!/bin/bash -e
 # vim: set filetype=sh:
 
 # abuild - build apk packages (light version of makepkg)
@@ -491,12 +491,12 @@ initdcheck() {
 		esac
 
 		case "$line" in
-		*sbin/openrc-run)
+		*usr/bin/openrc-run)
 			;;
-		*sbin/runscript)
-			warning "$i is not an openrc #!/sbin/openrc-run"
+		*usr/bin/runscript)
+			warning "$i is not an openrc #!/usr/bin/openrc-run"
 			;;
-		*)	error "$i is not an openrc #!/sbin/openrc-run"
+		*)	error "$i is not an openrc #!/usr/bin/openrc-run"
 			return 1
 			;;
 		esac
@@ -594,7 +594,7 @@ subpkg_set() {
 	subpkgarch=${_splitarch#*:}
 	if [ "$subpkgarch" = "$_splitarch" -o -z "$subpkgarch" ]; then
 		case "$subpkgname" in
-		*-doc | *-openrc | *-lang | *sh-completion | *-pyc | *-nftrules | *-systemd | *-udev) subpkgarch="noarch" ;;
+		*-doc | *-openrc | *-lang | *sh-completion) subpkgarch="noarch" ;;
 		*) subpkgarch="$pkgarch" ;;
 		esac
 	elif [ "$subpkgarch" = "all" ]; then
@@ -804,7 +804,7 @@ postcheck() {
 
 	# /usr merge
 	if ! options_has "!usrmerge"; then
-		for i in bin sbin lib; do
+		for i in bin sbin lib usr/sbin usr/libexec; do
 			if [ -L "$dir"/$i ] || [ -e "$dir"/$i ]; then
 				warning "Packages must not put anything under /$i, use /usr/${i##*s} instead"
 			fi
@@ -816,12 +816,6 @@ postcheck() {
 		find "$dir" -name '*.la' -type f -delete
 	fi
 
-	# look for /usr/lib/charset.alias
-	if [ -e "$dir"/usr/lib/charset.alias ] \
-			&& ! options_has "charset.alias"; then
-		error "Found /usr/lib/charset.alias"
-		e=1
-	fi
 	# look for /etc/init.d and /etc/conf.d
 	if [ -e "$dir"/etc/init.d -o -e "$dir"/etc/conf.d ] \
 			&& ! is_openrc_pkg "$name"; then
@@ -860,13 +854,6 @@ postcheck() {
 			e=1
 		fi
 	fi
-	# look for pycache
-	# wildcard should always get the system python dir, and this is faster than
-	# trying to calculate the python version.
-	i="$(find "$dir"/usr/lib/python* \( -type d -a -name "__pycache__" \) 2>/dev/null || :)"
-	if [ -n "$i" ] && [ "${name%-pyc}" = "$name" ]; then
-		warning "Found __pycache__ but package name doesn't end with -pyc"
-	fi
 
 	# check that we don't have any files names with newline
 	i=$(find "$dir" -name $'*\n*')
@@ -899,20 +886,6 @@ postcheck() {
 			e=1
 		fi
 	fi
-	# test capabilities on executables
-	# see: https://gitlab.alpinelinux.org/alpine/tsc/-/issues/45
-	getcap -r "$dir" | (local r=true execothers; while read -r line; do
-		local filename="${line% *}"
-		if ! options_has "setcap"; then
-			error "Found binary with extra capabilities: $filename"
-			r=false
-		fi
-
-		execothers="$(find "$filename" -perm -o+x)"
-		if [ -n "$execothers" ]; then
-			warning "Found setcap binary executable by others: $filename"
-		fi
-	done; $r) || e=1
 
 	# test for textrels
 	if ! options_has "textrels"; then
@@ -1467,7 +1440,7 @@ real_so_path() {
 		[ -e "$1"/$so ] && realpath "$1/$so" && return 0
 		shift
 	done
-	error "$so: path not found"
+	error "$so: shared library not found"
 	return 1
 }
 
@@ -1483,13 +1456,52 @@ find_so_files() {
 	return 0
 }
 
+subpkg_provides_prefixed_so() {
+	if [ -n "$sonameprefix" ] && grep -q -w "^$sonameprefix$1" \
+		"$pkgbasedir"/.control.*/.provides-so 2>/dev/null; then
+		grep -l -H -w "^$sonameprefix$1" \
+			"$pkgbasedir"/.control.*/.provides-so 2>/dev/null |
+			sed -e "s:^$pkgbasedir/\.control\.::" -e "s:/\.provides-so::" |
+			tr -d '\n'
+		return 0
+	else
+		return 1
+	fi
+}
+
 subpkg_provides_so() {
-	grep -q -w "^so:$1" "$pkgbasedir"/.control.*/.provides-so 2>/dev/null
+	if grep -q -w "^so:$1" "$pkgbasedir"/.control.*/.provides-so 2>/dev/null; then
+		grep -l -H -w "^so:$1" "$pkgbasedir"/.control.*/.provides-so 2>/dev/null |
+			sed -e "s:^$pkgbasedir/\.control\.::" -e "s:/\.provides-so::" |
+			tr -d '\n'
+		return 0
+	else
+		return 1
+	fi
+}
+
+subpkg_provides_prefixed_pc() {
+	if [ -n "$pcprefix" ] && grep -q -w "^so:$pcprefix$1" \
+		"$pkgbasedir"/.control.*/.provides-pc 2>/dev/null; then
+		grep -l -H -w "^so:$pcprefix$1" "$pkgbasedir"/.control.*/.provides-pc 2>/dev/null |
+ 			sed -e "s:^$pkgbasedir/\.control\.::" -e "s:/\.provides-pc::" |
+			tr -d '\n'
+		return 0
+	else
+		return 1
+	fi
 }
 
 subpkg_provides_pc() {
-	grep -q -w "^pc:${1%%[<>=]*}" "$pkgbasedir"/.control.*/.provides-pc \
-		2>/dev/null
+	if grep -q -w "^${1%%[<>=]*}" "$pkgbasedir"/.control.*/.provides-pc \
+			2>/dev/null; then
+		grep -l -H -w "^${1%%[<>=]*}" "$pkgbasedir"/.control.*/.provides-pc |
+ 			sed -e "s:^$pkgbasedir/\.control\.::" -e "s:/\.provides-pc::" |
+			tr -d '\n'
+		return 0
+	else
+		return 1
+	fi
 }
 
 trace_apk_deps() {
@@ -1510,11 +1522,14 @@ trace_apk_deps() {
 		autodeps="$autodeps pkgconfig"
 	fi
 
-	for i in $(cat "$dir"/.needs-so 2>/dev/null); do
-		if subpkg_provides_so "$sonameprefix$i"; then
-			autodeps="$autodeps so:$sonameprefix$i"
-		elif $APK $apkroot info --quiet -e "so:$i"; then
-			autodeps="$autodeps so:$i"
+	[ -f "$dir"/.needs-so ] && for i in $(cat "$dir"/.needs-so); do
+		# first check if its provided by same apkbuild
+		grep -q -w "^$sonameprefix$i" "$dir"/.provides-so 2>/dev/null && continue
+
+		if subpkg_provides_prefixed_so "$i">/dev/null; then
+			warning "subpkg so dependency missing: $i in $(subpkg_provides_prefixed_so $i)"
+		elif subpkg_provides_so "$i">/dev/null; then
+			warning "subpkg so dependency missing: $i in $(subpkg_provides_so $i)"
 		else
 			missing="$missing $i"
 		fi
@@ -1526,39 +1541,56 @@ trace_apk_deps() {
 		so_files=$(find_so_files "$dir"/.rpaths $missing)
 		deppkgs=$($APK $apkroot info --quiet --who-owns $so_files)
 		for found in $deppkgs; do
-			if grep -q -x -F "depend = $found" "$dir"/.PKGINFO; then
-				warning "You can remove '$found' from depends"
-				continue
-			fi
-			autodeps="$autodeps $found"
+		    if ! grep -w "^depend = ${found}$" "$dir"/.PKGINFO >/dev/null ; then
+			    warning "so dependency missing: $found"
+		    fi
 		done
 	fi
+
+	# symlink targets
+	for i in $(sort -u "$dir"/.symlinks-needs 2>/dev/null); do
+		autodeps="$autodeps $i"
+	done
+
+	# python3 dependencies
+	for i in $(sort -u "$dir"/.python3-needs 2>/dev/null); do
+		autodeps="$autodeps $i"
+	done
+
+	# debuginfo conflict dependencies
+	local ver=$pkgver-r$pkgrel
+	for i in $(sort -u "$dir"/.debug-target-pkgs 2>/dev/null); do
+		autodeps="$autodeps !$i<$ver !$i>$ver"
+	done
 
 	# pkg-config depends
 	local provider
 	for i in $(sort -u "$dir"/.needs-pc 2>/dev/null); do
-		if subpkg_provides_pc "$pcprefix$i"; then
+		# first check if its provided by same apkbuild
+		grep -q -w "^$pcprefix$i" "$dir"/.provides-pc 2>/dev/null && continue
+
+		if subpkg_provides_prefixed_pc "$i" >/dev/null; then
 			autodeps="$autodeps pc:$pcprefix$i"
-		elif $APK $apkroot info --quiet -e "pc:$i"; then
-			provider=$($APK $apkroot search --from installed --quiet --exact "pc:${i%%[<>=~]*}")
-			if list_has "$provider" $depends_dev; then
-				warning "$provider should be removed from depends_dev"
+			warning "subpkg pkg-config depdency missing: $i in $(subpkg_provides_prefixed_pc $i)"
+		elif subpkg_provides_pc "$i"; then
+			provider=$($APK $apkroot search --quiet --exact "pc:$i")
+			if ! list_has "$provider" $depends_dev; then
+				warning "subpkg pkg-config dependency missing: $i in $(subpkg_provides_pc $i)"
 			fi
-			autodeps="$autodeps pc:$i"
 		else
-			warning "Could not find any provider for pc:$i"
+			warning "pkg-config dependency missing: $i"
 		fi
 	done
 
 	echo "# automatically detected:" >> "$dir"/.PKGINFO
-
-	touch "$dir"/.provides-dummy
-	sed 's/^/provides = /' "$dir"/.provides-* | sort -u >> "$dir"/.PKGINFO
-
-	for i in "$dir"/.needs-symlinks "$dir"/.needs-python3 "$dir"/.needs-debug; do
-		[ -f "$i" ] && cat "$i"
-	done | sed 's/^/depend = /' | sort -u >> "$dir"/.PKGINFO
-
+	if [ -f "$dir"/.provides-pc ]; then
+		sed 's/^/provides = pc:/' "$dir"/.provides-pc | sort -u \
+			>> "$dir"/.PKGINFO
+	fi
+	if [ -f "$dir"/.provides-py ]; then
+		sed 's/^/provides = /' "$dir"/.provides-py | sort -u \
+			>> "$dir"/.PKGINFO
+	fi
 	for i in $autodeps; do
 		echo "depend = $i"
 	done | sort -u >> "$dir"/.PKGINFO
@@ -2183,32 +2215,6 @@ fishcomp() {
 	default_fishcomp
 }
 
-default_pyc() {
-	depends=
-	pkgdesc="Precompiled Python bytecode for ${subpkgname%-pyc}"
-	install_if="${subpkgname%-pyc}=$pkgver-r$pkgrel pyc"
-
-	cd "$pkgdir"
-	local IFS=$'\n'
-	amove $(find usr/lib/python* -type d -name __pycache__)
-}
-
-pyc() {
-	default_pyc
-}
-
-default_nftrules() {
-	depends=
-	pkgdesc="$pkgdesc (nftables ruleset)"
-	install_if="nftables-rulesets ${subpkgname%-nftrules}=$pkgver-r$pkgrel"
-
-	amove 'usr/share/nftables.avail/*.nft' || :
-}
-
-nftrules() {
-	default_nftrules
-}
-
 is_function() {
 	type "$1" 2>&1 | head -n 1 | grep -E -q "is a (shell )?function"
 }
@@ -2488,8 +2494,7 @@ rootbld_qemu_arch() {
 	case "$CBUILD_ARCH" in
 	arm*) qarch="arm" ;;
 	x86)  qarch="i386" ;;
-	loongarch*) qarch="loongarch" ;;
-	*)    qarch="$CBUILD_ARCH" ;;
+	*)	qarch="$CBUILD_ARCH" ;;
 	esac
 
 	echo "${qarch}"
@@ -2931,8 +2936,8 @@ while getopts ":AcC:dD:fFhkKmnP:qrs:vV" opt; do
 	case $opt in
 		'A') echo "$CARCH"; exit 0;;
 		'c') enable_colors
-		     color_opt="-c";;
-		'C') cd "$OPTARG";;
+			 color_opt="-c";;
+		'C') chdir "$OPTARG";;
 		'd') nodeps="-d";;
 		'D') DESCRIPTION=$OPTARG;;
 		'f') force="-f";;
@@ -2941,7 +2946,7 @@ while getopts ":AcC:dD:fFhkKmnP:qrs:vV" opt; do
 		'k') keep="-k";;
 		'K') keep_build="-K";;
 		'm') disable_colors
-		     color_opt="-m";;
+			 color_opt="-m";;
 		'n') die "Use newapkbuild to create new aports";;
 		'P') REPODEST=$OPTARG;;
 		'q') quiet="-q";;
